const dummyUsersList = [
  {
    id: "0000",
    name: "Gandalf",
    userName: "Gandalf",
    email: "gandalf@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Gandalf",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Gandalf600ppx.jpg",
  },
  {
    id: "0001",
    name: "Aragorn",
    userName: "Aragorn",
    email: "aragorn@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Aragorn",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Aragorn300ppx.png",
  },
  {
    id: "0002",
    name: "Legolas",
    userName: "Legolas",
    email: "legolas@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Legolas",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Legolas600ppx.jpg",
  },
  {
    id: "0003",
    name: "Gimli",
    userName: "Gimli",
    email: "gimli@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Gimli_(Middle-earth)",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Gimli_With_Axe.jpg",
  },
  {
    id: "0004",
    name: "Boromir",
    userName: "Boromir",
    email: "boromir@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Boromir",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Vlcsnap-bormir.png",
  },
  {
    id: "0005",
    name: "Meriadoc",
    userName: "Merry",
    email: "merry@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Merry_Brandybuck",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Meriadoc_Brandybuck_screenshot.jpg",
  },
  {
    id: "0006",
    name: "Peregrin",
    userName: "Pippin",
    email: "pippin@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Pippin_Took",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Pippinprintscreen.jpg",
  },
  {
    id: "0007",
    name: "Samwise",
    userName: "Sam",
    email: "sam@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Samwise_Gamgee",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Sean_Astin_as_Samwise_Gamgee.png",
  },
  {
    id: "0008",
    name: "Frodo",
    userName: "Frodo",
    email: "frodo@middle-earth.de",
    webProfileUrl: "https://en.wikipedia.org/wiki/Frodo_Baggins",
    avatarUrl: "https://en.wikipedia.org/wiki/File:Elijah_Wood_as_Frodo_Baggins.png",
  },
];

export default dummyUsersList;
